# Generated by Django 5.0.6 on 2024-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('details', models.TextField(verbose_name='Details')),
            ],
        ),
    ]
