# Generated by Django 5.0.6 on 2024-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Is Priority'),
        ),
    ]
