# Generated by Django 5.0.6 on 2024-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todotask_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is Done Task'),
        ),
    ]
